## -----------------------------------------------------------------------------
## Global Requires
## -----------------------------------------------------------------------------
require 'rake'

## -----------------------------------------------------------------------------
## Globals
## -----------------------------------------------------------------------------
RAKE_DIR    = File.dirname(__FILE__)
TASKS_DIR   = File.join(RAKE_DIR, '_tasks')
LIB_DIR     = File.join(RAKE_DIR, '_include')
$LOAD_PATH.push LIB_DIR

## -----------------------------------------------------------------------------
## Local Requires
## -----------------------------------------------------------------------------
require 'rake/ask'

## -----------------------------------------------------------------------------
## Main
## -----------------------------------------------------------------------------
rake_files = Rake::FileList.new.
               include("#{TASKS_DIR}/*.rake").
               include("#{TASKS_DIR}/*/*.rake")
rake_files.each { |x| load x }

task :default => :help

desc 'Build all available packages'
task 'package:ALL' do
  Rake.application.tasks.each do |task|
    task.invoke if task.name.match(%r{package:.*?:default})
  end
end

task 'package:all' => 'package:ALL'

task :help do
  puts
  puts "Run '#{$0} -T' to see all available tasks"
  puts
end
